#!/usr/bin/env php

<?php

$opts = getopt("b:");

$birthDate = $opts["b"]; // "1976-07-11";
$todayDate = date("Y-m-d");

$birthTime = strtotime($birthDate);
$todayTime = strtotime($todayDate);

$totalsecs = $todayTime - $birthTime;
$totalDays = floor($totalsecs / 3600 /24);

echo"$birthDate : $totalDays\n";

