#!/usr/bin/env php

<?php

include "src/Dates/BirthDays.php";

$birthDate = "1976-07-11";
$days = new \Levchenko\Dates\BirthDays($birthDate) ;//\Levchenko\slaventiy76\
$totalDays = $days->findTotalDays();
echo"$birthDate : $totalDays\n";

